name: Generate CBOM with cdxgen for Docker Images

on:
  workflow_dispatch:
    inputs:
      src_repository:
        description: 'Docker Images Repository'
        required: true
        default: ''
      src_type:
        description: 'Project Type (docker, container)'
        required: false
        default: 'java'
jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Install cdxgen
        run: |
          npm install -g @cyclonedx/cdxgen
      - name: Generate CBOM
        run: cdxgen -o cbom.json --include-crypto -t ${{ inputs.src_type }} ${{ inputs.src_repository }}
      - name: list files
        run: ls -la
      - name: Upload Scan Results
        uses: actions/upload-artifact@v4
        with:
          name: cbom
          path: cbom.json
