name: cdxgen and Trivy from src

on:
  workflow_dispatch:
    inputs:
      src_repository:
        description: 'Source Repository'
        required: true
        default: ''
      src_branch:
        description: 'Branch'
        required: false
        default: ''
      src_type:
        description: 'Project Type (java, python, dotnet) see https://cyclonedx.github.io/cdxgen/#/PROJECT_TYPES'
        required: false
        default: 'java'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.src_repository }}
          ref: ${{ inputs.src_branch }}
    
      - name: Generate SBOM using cdxgen container
        run: |
          docker run --rm \
            -v "$(pwd)":/app:rw \
            -v /tmp:/tmp \
            -t ghcr.io/cyclonedx/cdxgen:latest \
            -r /app -o /tmp/sbom.json -t ${{ inputs.src_type }} \
            --profile ${{ inputs.src_profile }} --json-pretty
        
      - name: Scan SBOM with trivy
        run: |
          docker run --rm \
            -v "$(pwd)":/app:rw \
            -v /tmp:/tmp \
            -t docker.io/aquasec/trivy:latest sbom \
            --format "cyclonedx" \
            --scanners vuln,license \
            --output /tmp/trivy-report-cdxgen-src.json \
            /tmp/sbom.json

      - name: artifact name
        id: artifactname
        run: |
          out_name="${{ inputs.src_repository }}"
          out_name="${out_name//\//-}"  # Replace '/' with '-'
          echo "out_name=$out_name" >> $GITHUB_OUTPUT

      - name: Upload SBOM results
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.artifactname.outputs.out_name }}
          path: /tmp/*.json
          if-no-files-found: warn
