name: Verify vulnerabilities from sbom with depscan (ver. docker)

on:
  workflow_dispatch:
    inputs:
      src_repository:
        description: 'Source Repository'
        required: true
        default: ''
      src_branch:
        description: 'Branch'
        required: false
        default: ''
      src_sbom:
        description: 'sbom file name'
        required: false
        default: 'sbom.json'
env:
  OUTPUT_NAME: 'cyclonedxSBOM'
jobs:
  sbom:
    runs-on: ubuntu-latest

    steps:
    - name: free space at beginning
      run: df -h
      
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.src_repository }}
        ref: ${{ inputs.src_branch }}

    - name: free space after checkout
      run: df -h
    
    - name: list files
      run: ls -la

    #OPTIONS:
    #-e USE_VDB_10Y=true
    #-e VDB_DATABASE_URL=ghcr.io/appthreat/vdbxz-app:v6
    - name: Scan SBOM with depscan
      run: |
        docker run --rm \
          -e VDB_DATABASE_URL=ghcr.io/appthreat/vdbxz-app:v6 \
          -v .:/app ghcr.io/owasp-dep-scan/dep-scan \
          --debug \
          --bom /app/${{ inputs.src_sbom }} \
          --report-template /app/${{ inputs.src_sbom }} \
          --reports-dir /app

    - name: list files
      run: ls -la

    - name: free space after dep-scan
      run: df -h
    
    - name: Upload SBOM results
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.OUTPUT_NAME }}
        path: ${{github.workspace}}/*.json 
