name: Legitify Analyze
on:
    workflow_dispatch:
    #schedule:
    #  - cron: '0 11 * * 1-5'

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Legitify Action
        uses: Legit-Labs/legitify@v1.0.7
        with:
          github_token: ${{ secrets.TEST_TOKEN }}
          ignore-policies: |
             non_admins_can_create_public_repositories
             requires_status_checks
          output-format: human-readable
          output-file: legify-report.txt
