name: Legitify Analyze
on:
    workflow_dispatch:
    #schedule:
    #  - cron: '0 11 * * 1-5'

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      #- name: Legitify Action
      #  uses: Legit-Labs/legitify@v1.0.7
      #  with:
      #    github_token: ${{ secrets.TEST_TOKEN }}
      #    ignore-policies: |
      #       non_admins_can_create_public_repositories
      #       requires_status_checks
      #    output-format: human-readable
      #    output-file: legitify-report.txt
      
     - uses: actions/cache@v4
       with:
        path: |
          legitify
        key: ${{ runner.os }}-legitify-1.0.7
     - name: Legitify Scan - CLI
       run: |
          if [[ -f "legitify" ]]; then
             ./legitify analyze --token=${{ secrets.TEST_TOKEN }} --output-file legitify-report.txt
          else
             wget https://legitify.legitsecurity.com/1.0.7/linux/amd64.tar.gz
             tar -xzf amd64.tar.gz
             ./legitify analyze --token=${{ secrets.TEST_TOKEN }} --output-file legitify-report.txt
          fi
     - name: Upload Result
       uses: actions/upload-artifact@v2
       with:
         name: legitify-report.txt
         path: legitify-report.txt
     - name: Upload Error Log
       uses: actions/upload-artifact@v2
       with:
         name: legitify-error.log
         path: legitify-error.log
      
